#!/usr/bin/env bash
# Rebuilds assets/vendor/supabase-slim.mjs: Supabase's official auth + database
# clients (MIT licensed) as one small browser module. Run to upgrade versions.
set -euo pipefail
VERSION="${1:-2.117.2}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cd "$TMP"
npm init -y >/dev/null
npm install --silent "@supabase/auth-js@$VERSION" "@supabase/postgrest-js@$VERSION" esbuild >/dev/null
echo 'export { AuthClient } from "@supabase/auth-js"; export { PostgrestClient } from "@supabase/postgrest-js";' > entry.js
{
  echo "// @supabase/auth-js + @supabase/postgrest-js v$VERSION (MIT License, (c) Supabase)."
  echo "// Generated by scripts/vendor-supabase.sh — do not edit by hand."
  npx esbuild entry.js --bundle --format=esm --minify --target=es2020 --platform=browser --legal-comments=none
} > "$ROOT/assets/vendor/supabase-slim.mjs"
echo "Wrote assets/vendor/supabase-slim.mjs ($(wc -c < "$ROOT/assets/vendor/supabase-slim.mjs") bytes)"
